#!/bin/sh

set -e

main () {
  TW5="$(readlink -f "$(which tiddlywiki)")"
  if [ -n "$NODE_MEM" ]; then
    NODE_OPTIONS="--max_old_space_size=$(( ( NODE_MEM * 4 ) / 5 )) \
                  $NODE_OPTIONS"
    export NODE_OPTIONS
  fi

  if [ ! -d "/var/lib/tiddlywiki/$TW_WIKINAME" ]; then
    /usr/bin/env node "$TW5" "$TW_WIKINAME" --init server
  fi

  # shellcheck disable=SC2086
  exec /usr/bin/env node $NODE_OPTIONS "$TW5" "$TW_WIKINAME" --listen \
      port="$TW_PORT" \
      host="$TW_HOST" \
      root-tiddler="$TW_ROOTTIDDLER" \
      render-type="$TW_RENDERTYPE" \
      serve-type="$TW_SERVETYPE" \
      path-prefix="$TW_PATHPREFIX" \
      tls-key="../tw_key.pem" \
      tls-cert="../tw_server.crt" \
      credentials="../tw_credentials.csv"
      
}

main "$@"
